### ISSUE TITLE
Line 1: warning: file is not gofmted with -s (gofmt)

### ISSUE THREAD

**Issue by jsmith-dev** [gojp/goreportcard#202]
Line one is often a comment (i.e):

// Welcome to MyGoApp this file is blah, blah, blah.

Q: Why is a comment line on line one (1) captured for warning on 'gofmted' basis?
Q: Is the suggestion that comments are to be avoided or wrapped in 'gofmt' ??
Q: by design or false positive?

**Comment by shawnps** [comment]
@jsmith-dev when you have a moment could you link to an example repo please? Thanks!

**Comment by hermanschaaf** [comment]
@jsmith-dev I suspect you are being misled by the error being on line 1: the error message is trying to say that the entire file is not `gofmt`-ed. It is not necessarily specific to the comment in your file, or to line 1 in particular :smile: 

You should be able to fix it with `gofmt -s -w <your file>.go`

**Comment by jsmith-dev** [comment]
oh. Right. Makes more sense.

**Comment by shawnps** [comment]
I'm gonna reopen this because the Line 1 thing is misleading. We should fix the message to say the whole file needs gofmt.

**Comment by zbintliff** [comment]
I'm also think there may be an issue:
https://goreportcard.com/report/github.com/pact-foundation/pact-go#gofmt

The above says:
```
Gofmt formats Go programs. We run gofmt -s on your code, where -s is for the "simplify" command

        pact-go/dsl/mock_service.go
        Line 1: warning: file is not gofmted (gofmt)
```

but when I pull down the files and run fmt there is no change:
```
[pact-go/ (master)]$ git pull
Already up-to-date.
[pact-go/ (master)]$ git rev-parse HEAD
f1f0d7644204c77c5e35ed7fec2806342221cdb8
[pact-go/ (master)]$ gofmt -s -w dsl/mock_service.go
[pact-go/ (master)]$ git st
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
```

Granted, when i run `gofmt -s dsl/mock_service.go` I do get output:
```
[pact-go/ (master)]$ gofmt -s dsl/mock_service.go | wc
     115     387    3153
```

I even written it to another file and diff them, with no change:
```
[pact-go/ (master)]$ gofmt -s dsl/mock_service.go > test.go
[pact-go/ (master)]$ git diff test.go dsl/mock_service.go
[pact-go/ (master)]$ echo $?
0
```

Which may point to an issue with `gofmt` and not necessarily your project.

**Comment by hermanschaaf** [comment]
@zbintliff We cache repositories on Go Report Card so that we don't have to do a fresh `git pull` on every page load. This is indicated in the left-hand panel, where it says "Last refresh 1 year ago". I clicked the refresh button on your page and now the `gofmt` error on `mock_service` is no longer there, but there are some other files. So I think your issue was just one of caching. 

We have another issue tracking the fact that caching is not made obvious enough, and could definitely be improved: https://github.com/gojp/goreportcard/issues/66

**Comment by didenko** [comment]
The issue does not seem to be related to (only) caching. Consider https://goreportcard.com/report/go.didenko.com/fst, which as of ***now*** still show that message:

![2017-12-14 15 57 51](https://user-images.githubusercontent.com/99670/34016518-ce7fe1e6-e0e7-11e7-94b6-0a0bc95cddb0.jpg)

Yet local `gofmt` finds no differences:

![2017-12-14 16 00 27](https://user-images.githubusercontent.com/99670/34016613-2bf7b7ae-e0e8-11e7-9137-990cd5c91ce2.jpg)

It is running on go version go1.9.2 darwin/amd64.

**Comment by fredbi** [comment]
This false positive problem on simple go fmt issue is really annoying.
It looks like that the code in master has merged a fix for this. Do you plan to deploy this version on the goreportcard.com site any time soon?

**Comment by AkashEMC** [comment]
phasing the same issue what zbintliff has mentioned above. any resolution ??

**Comment by shawnps** [comment]
@AkashEMC could you link a sample repo, please? Thanks

**Comment by AkashEMC** [comment]
@shawnps sorry for late reply, my issue got resolved, it was due to missing Unit test cases along with code.

**Comment by ohir** [comment]
Pity to write "metoo" but the "gofmt -s" test is just broken. I do have `gofmt -s` on write (with vim-go). So there is no way I could commit not formatted code.
Sample repo: https://github.com/ohir/bitpeek

**Comment by shawnps** [comment]
> Pity to write "metoo" but the "gofmt -s" test is just broken. I do have gofmt -s on write (with vim-go). So there is no way I could commit not formatted code.

Hi @ohir:

1. Click Format on this: https://play.golang.org/p/E0jMFat2z2k and you'll see that the space after "MIT" in the comment is removed.
2. Click Format on this: https://play.golang.org/p/Hh1OtkF_KEg and you'll see issues with the alignment of comments.

**Comment by ohir** [comment]
OK. Seems that there is refactoring of gofmt under way and new one is smarter about comments.
For bitpeek publishing and yesterday's checks I used `go version devel +f2131f6e0c`.

I checked now with `go version go1.10.3` and indeed older (but release/official) gofmt produces what you pointed. Space slipped in because the (c) header I put via sed right before publishing. It hadn't got a chance to be reformatted via vim hook. Nor the ad-hoc repo had gofmt commit hook in place. 

So its my fault. Sincere apologies to you, guys.

P.S. It would be a good point to the FAQ though, something like "We use current release version of gofmt. Your devel or old version might produce other output."

**Comment by shawnps** [comment]
> So its my fault. Sincere apologies to you, guys.

No problem :) thanks for using Go Report Card and for being actively involved in making it better.

> P.S. It would be a good point to the FAQ though, something like "We use current release version of gofmt. Your devel or old version might produce other output."

This is a nice idea, I'd like to have a page on Go Report Card that shows which versions of linters and Go we're using.

**Comment by carstenhag** [comment]
I don't understand how I can fix this problem.  
https://goreportcard.com/report/gitlab.com/K-AI/it4me

`go fmt ./...` finds no issues on my project.  
`gofmt -s cmd/pullmails/pullmails.go` prints out the program. No clue how to automate this.

**Comment by shawnps** [comment]
@carstenhag It seems like upgrading the Go version to 1.11 on the server fixed the issue. Please check again to confirm.
